language: ruby
rvm:
  - 2.4.0

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system
  - gem install bundler

before_script:
  - psql -c "CREATE USER \"rails-bootstrap\" WITH PASSWORD 'rails-bootstrap';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"rails-bootstrap_test\";" -U postgres
  - psql -c "CREATE DATABASE \"rails-bootstrap_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rubocop --require rubocop-rails app spec

cache:
  bundler: true
